<?php
/**
 * Copyright © 2023 Anton Abramchenko. All rights reserved.
 *
 * Redistribution and use permitted under the BSD-3-Clause license.
 * For full details, see COPYING.txt.
 *
 * @author    Anton Abramchenko <anton.abramchenko@labofgood.com>
 * @copyright 2023 Anton Abramchenko
 * @license   See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block  */
/** @var \Magento\Framework\Escaper $escaper  */
/** @var \Labofgood\EngraveProduct\ViewModel\Product\EngraveProductForm $viewModel */

$viewModel = $block->getData('engrave_view_model');
?>

<?php if ($viewModel->isDisplayEngravingOption()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Labofgood_EngraveProduct/js/engrave-product-form": {
                    "wrapperSelector": ".product-info-main",
                    "displayCheckboxSelector": ".engrave-product-display",
                    "engraveTextareaSelector": ".engrave-product-textarea",
                    "addToCartFormSelector": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
