<?php
/**
 * Copyright © 2023 Anton Abramchenko. All rights reserved.
 *
 * Redistribution and use permitted under the BSD-3-Clause license.
 * For full details, see COPYING.txt.
 *
 * @author    Anton Abramchenko <anton.abramchenko@labofgood.com>
 * @copyright 2023 Anton Abramchenko
 * @license   See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block  */
/** @var \Magento\Framework\Escaper $escaper  */
/** @var \Labofgood\EngraveProduct\ViewModel\Product\EngraveProductForm $viewModel */

$viewModel = $block->getData('engrave_view_model');
?>

<?php if ($viewModel->isDisplayEngravingOption()): ?>
<div class="engrave-product-form-wrapper">
    <form class="engrave-product-form" action="#">
        <div class="engrave-product-checkbox">
            <input id="engrave-product-display" type="checkbox" class="engrave-product-display"
                   name="engrave_product[is_display]" value="0"/>
            <label for="engrave-product-display">
                <?= /* @noEscape */ __('Add engraving text?') ?>
            </label>
        </div>
        <div style="display: none" class="engrave-product-textarea">
            <label for="engrave-product-textarea-value">
                <?= /* @noEscape */ __('Engraving text') ?>
            </label>
            <textarea id="engrave-product-textarea-value" class="engrave-product-textarea-value"
                      name="engrave_product[text]" rows="5" cols="5"></textarea>
        </div>
    </form>
</div>
<?php endif; ?>
